version: '3'
services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile:
        frontend.dockerfile
    ports:
      - "3000:3000"
    links:
      - backend
    restart: always

  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile:
        backend.dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_URL=mysql://root:root@host.docker.internal:3306/library

  db:
    container_name: db
    image: mysql:oracle
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library